# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cypress/base:10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-deps-{ .Branch }-{ checksum "package.json" }
            - v1-deps-{ .Branch }
            - v1-deps

      - run: npm ci

      - save_cache:
          paths:
            - ~/.cache
            - ~/.npm
          key: v1-deps-{ .Branch }-{ checksum "package.json" }

      - run:
          name: clear cypress cache
          command: yarn cy:clear

      - run:
          name: Running ETE tests
          command: yarn cy:ci

      - run:
          name: Build
          command: yarn build

      - run:
          name: Deploy to Netlify
          command: yarn netlify:deploy
